# Load theme (Ensure this file exists in the same folder)
# include active-theme.conf

foreground                      #BBBBBB
background                      #191919
selection_foreground            #BBBBBB
selection_background            #404040
# Cursor colors
cursor                          #C9C9C9
cursor_text_color               #191919
active_tab_foreground           #BBBBBB
active_tab_background           #65435E
inactive_tab_foreground         #BBBBBB
inactive_tab_background         #303030
# black
color0 #191919
color8 #3D3839
# red
color1 #DE6E7C
color9 #E8838F
# green
color2  #819B69
color10 #8BAE68
# yellow
color3  #B77E64
color11 #D68C67
# blue
color4  #6099C0
color12 #61ABDA
# magenta
color5  #B279A7
color13 #CF86C1
# cyan
color6  #66A5AD
color14 #65B8C1
# white
color7  #BBBBBB
color15 #8E8E8E


# Cursor
cursor_shape beam
cursor_trail 1

# Padding (why weird value? consistency with foot)
window_margin_width 21.75

# No stupid close confirmation
confirm_os_window_close 0

# Copy to clipboard (copies if text is selected, otherwise sends SIGINT)
map ctrl+c copy_or_interrupt
# Paste from clipboard
map ctrl+v paste_from_clipboard

# macOS Shell Logic (Optimized for Homebrew tmux)
shell zsh --login -c "if command -v tmux >/dev/null 2>&1; then tmux attach || tmux; else zsh; fi"

# macOS Specific UI
hide_window_decorations titlebar-only
background_opacity 0.8
background_blur 6

# --- Fonts ---
font_size        14.0
font_family      FiraMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_features    +liga
enable_ligatures true

# --- General Settings ---
scrollback_lines 100000
allow_remote_control yes
editor .
confirm_os_window_close 0
enable_audio_bell no
window_padding_width 8 15 8 15

# --- Mouse Mapping ---
mouse_map left click no_op
mouse_map left doubleclick no_op

# --- Key Mappings ---
# Send codes for tmux ctrl+tab
map ctrl+tab send_text all \x1b[27;5;9~
map ctrl+shift+tab send_text all \x1b[27;6;9~

# Disable reload config shortcut
map ctrl+shift+r no_op

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down
